version: '2.1'

services:
    api:
        build: .
        ports:
            - "9000:9000"
        depends_on:
            redis:
                condition: service_healthy
            mysql:
                condition: service_healthy

    redis:
        image: redis
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli","ping"]
            interval: 10s
            timeout: 10s
            retries: 10
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass

        volumes:
            - "./db/data:/var/lib/mysql"
            - "./db/init:/docker-entrypoint-initdb.d"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 10s
            timeout: 10s
            retries: 10
