version: '2.1'

services:
    api:
        build: .
        ports:
            - "9000:9000"
        depends_on:
            redis:
                condition: service_healthy
            mysql:
                condition: service_healthy

    redis:
        image: redis
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli","ping"]
            interval: 30s
            timeout: 10s
            retries: 3
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
